
#include <string>
#include <boost/filesystem.hpp>
#include "fstream_utf8.h"
#include "log_sched.h"

#define GRIS_CLARO "#dedede"
#define GRIS_OSCURO "#666666"

static std::string css_style_ = "/* Built in style for main */\n\n"
"body {\n"
"	font-family: verdana,arial,sans-serif;\n"
"	font-size: 12px;\n"
"	color: #333333;\n"
"	border-width: 0px;\n"
"	padding: 0px;\n"
"}\n"
".in_process {\n"
"	font-family: courier;\n"
"	font-size: 12px;\n"
"	color: #222222;\n"
"}\n"
"table.in_process {\n"
"	margin: 12px;\n"
"}\n"
"table.in_process th {\n"
"	text-align: center;\n"
"}\n"
"canvas {\n"
"	border-width: 0px;\n"
"	padding: 0px;\n"
"}\n"
"th {\n"
"   text-align: left;\n"
"}\n"
"table.diffstats {\n"
"	margin: 12px;\n"
"	font-family: courier;\n"
"}\n"
"table.gridtable {\n"
"	font-family: verdana,arial,sans-serif;\n"
"	font-size: 11px;\n"
"	color: #333333;\n"
"	border-width: 1px;\n"
"	border-color: " GRIS_OSCURO ";\n"
"	border-collapse: collapse;\n"
"}\n"
"table.gridtable th {\n"
"	border-width: 1px;\n"
"	padding: 8px;\n"
"	border-style: solid;\n"
"	border-color: " GRIS_OSCURO ";\n"
"	background-color: " GRIS_CLARO ";\n"
"}\n"
"table.gridtable td {\n"
"	border-width: 1px;\n"
"	padding: 8px;\n"
"	border-style: solid;\n"
"	border-color: " GRIS_OSCURO ";\n"
"	background-color: #ffffff;\n"
"}\n"
"table.report {\n"
"	width:100%;\n"
"	display:block;\n"
"	height:auto;\n"
"	border-collapse:collapse;\n"
"	font-size:9pt;\n"
"}\n"
"table.report th {\n"
"	height:25px;\n"
"	text-align:left;\n"
"	background-color:#585858;\n"
"	color:white;\n"
"	padding:10px 20px 5px 20px;\n"
"}\n"
"table.report td {\n"
"	padding:10px 20px 5px 20px;\n"
"	border-bottom:1px solid #585858;\n"
"	background-color: #F7F5F7;\n"
"	vertical-align:top;\n"
"}\n"
"table.new_db {\n"
"	background-color: #e6e600;\n"
"	padding: 10px;\n"
"	border-style: solid;\n"
"	border-width: 1px;\n"
"	border-color: #999900;\n"
"}\n"
"table.new_ptask {\n"
"	background-color: #ffb3d1;\n"
"	padding: 6px;\n"
"	border-style: solid;\n"
"	border-width: 2px;\n"
"	border-color: #cc0052;\n"
"}\n"
"table.wizard {\n"
"	background: #FFFFFF;\n"
"	margin: 1.5em auto;\n"
"	padding: 1.85em 1em;\n"
"	width: 48em;\n"
//"	border: thin solid;\n"
//"	border-color: #DDDACF #CCC8B8 #BBB59F;\n"
"	box-shadow: 0 0.1em 0.3em #999900;\n"
"	border-radius: 0.5em;\n"
"	color: #33290A;\n"
"}\n"
"h2.wizard {\n"
"	color: #33290A;\n"
"	text-align: center;\n"
"}\n"
"p.wizard {\n"
"	color: #33290A;\n"
"	text-align: center;\n"
"	font-size: 14px;\n"
"}\n"
"strong.wizard {\n"
"	font-size: 20px;\n"
"	font-weight: bold;\n"
"}\n"
"td.graph {\n"
"	padding: 10px;\n"
//"	border: thin solid;\n"
//"	border-color: #DDDACF #CCC8B8 #BBB59F;\n"
"	box-shadow: 0 0.1em 0.3em #CCC8B8;\n"
"	border-radius: 0.5em;\n"
"}\n"
"td.perf {\n"
"	background: #F7FFF7;\n"
"}\n"
"td.counts {\n"
"	background: #F7F7FF;\n"
"}\n"
".ml {\n"
"   font: bold 11px Arial;\n"
"   text-decoration: none;\n"
"   background-color: #EEEEEE;\n"
"   color: #333333;\n"
"   padding: 2px 6px 2px 6px;\n"
"   border-top: 1px solid #CCCCCC;\n"
"   border-right: 1px solid #333333;\n"
"   border-bottom: 1px solid #333333;\n"
"   border-left: 1px solid #CCCCCC;\n"
"}\n"
"input[type=text] {\n"
"   padding:2px;\n"
"   border:2px solid #ccc;\n"
"   -webkit-border-radius: 5px;\n"
"   border-radius: 5px;\n"
"}\n"
"input[type=text]:focus {\n"
"   border-color:#333;\n"
"}\n"
"select {\n"
"   padding:2px;\n"
"   border:2px solid #ccc;\n"
"   -webkit-border-radius: 5px;\n"
"   border-radius: 5px;\n"
"}\n"
"select:focus {\n"
"   border-color:#333;\n"
"}\n"
"input[type=submit] {\n"
"   font: bold 12px Arial;\n"
"   text-decoration: none;\n"
"   padding:2px;\n"
"   padding: 3px 5px 1px 5px;\n"
"   background:#ccc;\n"
"   border:2px solid #ccc;\n"
"   cursor:pointer;\n"
"   -webkit-border-radius: 5px;\n"
"   border-radius: 5px;\n"
"}\n"
"input[type=submit]:focus, input[type=submit]:hover {\n"
"   border:2px solid #333;\n"
"}\n"
"h3 {\n"
"   margin: 10px;\n"
"   padding: 5px;\n"
"}\n"
"ul.filelist {\n"
"   list-style-type: none;\n"
"   margin: 20px;\n"
"   padding: 0px;\n"
"}\n"
"ul.filelist a {\n"
"   text-decoration: none;\n"
"   color: #000;\n"
"   font-size: 13px;\n"
"   margin: 5px;\n"
"}\n"
"ul.filelist a:hover {\n"
"   font-size: 15px;\n"
"   background: #eee;\n"
"   text-decoration: none;\n"
"   font-weight: bold;\n"
"}\n"
"ul.filelist a strong {\n"
"   color: blue;\n"
"   font-weight: normal;\n"
"}\n"
"ul.filelist a:hover strong {\n"
"   font-weight: bold;\n"
"}\n"
".dropbtn {\n"
"   background-color: #888888;\n"
"   color: white;\n"
"   padding: 4px;\n"
"   font-size: 9px;\n"
"   border: none;\n"
"   cursor: pointer;\n"
"}\n"
".dropbtn:hover, .dropbtn:focus {\n"
"   background-color: #444444;\n"
"}\n"
".dropdown {\n"
"   position: relative;\n"
"   display: inline-block;\n"
"}\n"
".dropdown-content {\n"
"   display: none;\n"
"   position: absolute;\n"
"   background-color: #f9f9f9;\n"
"   min-width: 80px;\n"
"   overflow: auto;\n"
"   box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\n"
"}\n"
".dropdown-content a {\n"
"   color: black;\n"
"   padding: 6px 8px;\n"
"   text-decoration: none;\n"
"   display: block;\n"
"}\n"
".dropdown a:hover {background-color: #f1f1f1}\n"
".show {display:block;}\n"
;


#define STYLES_FNAME "main.css"

void styles_load()
{
    try {
        ifstream_utf8 ifs(STYLES_FNAME, ifstream_utf8::binary);
        if (ifs) {
            size_t n = boost::filesystem::file_size(STYLES_FNAME);
            if (n > 10) {
                css_style_.resize(n);
                ifs.read((char*)&(css_style_[0]), css_style_.size());
                ILOG << "styles_load(" STYLES_FNAME ")-> loaded " << n << " bytes";
            }
        }
    } catch (std::exception &e) {
        WLOG << "styles_load(" STYLES_FNAME ")-> error: " << e.what();
    }
}

const std::string &get_styles()
{
    return css_style_;
}

